version: '3.1'

services:

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    hostname: 'rosesystems.kr'
    ports:
      - 13306:3306
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: fhwm3400!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: fhwmdnjem7746!
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

#  volumes:
  #    - '/srv/mariadb:/etc/mysql'

  adminer:
    container_name: db-adminer
    image: adminer
    restart: always
    hostname: 'rosesystems.kr'
    network_mode: "bridge"
    ports:
      - 33344:8080
