version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jun24677
      MYSQL_DATABASE: jhjeon
      MYSQL_USER: jhjeon
      MYSQL_PASSWORD: jun24677
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql